const weapons = [
  {
    name: "Pistol",
    range: 350,
    dmg: 25,
    indexYPos: 150,
    bullets: 8,
    magazin: 8,
    reloading: false,
    bulletCount: 1,
    bulletSpread: 0,
  },
  {
    name: "Shotgun",
    range: 45,
    dmg: 13,
    indexYPos: 133,
    bullets: 4,
    magazin: 4,
    reloading: false,
    bulletCount: 10,
    bulletSpread: 6,
  },
  {
    name: "knive",
    range: 20,
    dmg: 100,
    indexYPos: 168,
    bullets: 1,
    magazin: 1,
    reloading: false,
    bulletCount: 10,
    bulletSpread: 16,
  },
  // {
  //   name: granade,
  //   range: 100,
  //   dmg: 100,
  //   indexYPos: 116,
  //   bullets: 1,
  //   magazin: 1,
  //   reloading: false,
  //   bulletCount: 1,
  //   bulletSpread: 0,
  // }  
];
