let groundSheet = new Image();
groundSheet.src = "../assets/ground.png";
let fullSheet = new Image();
fullSheet.src = "../assets/tileset.png";
let obstacleSheet = new Image();
obstacleSheet.src = "../assets/obsticle.png";
let natureSheet = new Image();
natureSheet.src = "../assets/nature.png";
let streetSheet = new Image();
streetSheet.src = "../assets/street.png";
let house1Sheet = new Image();
house1Sheet.src = "../assets/house1.png";
let house2Sheet = new Image();
house2Sheet.src = "../assets/house2.png";
let acherSheet = new Image();
acherSheet.src = "../assets/achers.png";
let acher2Sheet = new Image();
acher2Sheet.src = "../assets/achers2.png";
let vendorSheet = new Image();
vendorSheet.src = "../assets/vendor.png";

let restSheet = new Image();
restSheet.src = "../assets/rest.png";
let rest2Sheet = new Image();
rest2Sheet.src = "../assets/rest2.png";
let waterSheet = new Image();
waterSheet.src = "../assets/water.png";

let zero = new Image();
zero.src = "../assets/0.png";
// let groundSheet = new Image();
// groundSheet.src = "../assets/ground.png";

const mapDefinition = [
  { index: 0, src: zero, x: 0, y: 0, pass: true, spawn: false },
  { index: 1, src: groundSheet, x: 0, y: 0, pass: true, spawn: false },
  { index: 2, src: groundSheet, x: 17, y: 0, pass: true, spawn: false },
  { index: 3, src: groundSheet, x: 34, y: 0, pass: true, spawn: false },
  { index: 4, src: groundSheet, x: 51, y: 0, pass: true, spawn: false },
  { index: 5, src: groundSheet, x: 68, y: 0, pass: true, spawn: false },
  { index: 6, src: groundSheet, x: 85, y: 0, pass: true, spawn: true },
  { index: 7, src: groundSheet, x: 0, y: 17, pass: true, spawn: false },
  { index: 8, src: groundSheet, x: 17, y: 17, pass: true, spawn: false },
  { index: 9, src: groundSheet, x: 34, y: 17, pass: true, spawn: false },
  { index: 10, src: groundSheet, x: 51, y: 17, pass: true, spawn: false },
  { index: 11, src: groundSheet, x: 68, y: 17, pass: true, spawn: false },
  { index: 12, src: groundSheet, x: 85, y: 17, pass: true, spawn: false },
  { index: 13, src: groundSheet, x: 0, y: 34, pass: true, spawn: false },
  { index: 14, src: groundSheet, x: 17, y: 34, pass: true, spawn: false },
  { index: 15, src: groundSheet, x: 34, y: 34, pass: true, spawn: false },
  { index: 16, src: groundSheet, x: 51, y: 34, pass: true, spawn: false },
  { index: 17, src: groundSheet, x: 68, y: 34, pass: true, spawn: false },
  { index: 18, src: groundSheet, x: 85, y: 34, pass: true, spawn: false },

  { index: 19, src: natureSheet, x: 0, y: 0, pass: false, spawn: false },
  { index: 20, src: natureSheet, x: 17, y: 0, pass: false, spawn: false },
  { index: 21, src: natureSheet, x: 34, y: 0, pass: false, spawn: false },
  { index: 22, src: natureSheet, x: 51, y: 0, pass: false, spawn: false },
  { index: 23, src: natureSheet, x: 68, y: 0, pass: false, spawn: false },
  { index: 24, src: natureSheet, x: 85, y: 0, pass: false, spawn: false },
  { index: 25, src: natureSheet, x: 0, y: 17, pass: false, spawn: false },
  { index: 26, src: natureSheet, x: 17, y: 17, pass: false, spawn: false },
  { index: 27, src: natureSheet, x: 34, y: 17, pass: false, spawn: false },
  { index: 28, src: natureSheet, x: 51, y: 17, pass: false, spawn: false },
  { index: 29, src: natureSheet, x: 68, y: 17, pass: false, spawn: false },
  { index: 30, src: natureSheet, x: 85, y: 17, pass: false, spawn: false },
  { index: 31, src: natureSheet, x: 0, y: 34, pass: false, spawn: false },
  { index: 32, src: natureSheet, x: 17, y: 34, pass: false, spawn: false },
  { index: 33, src: natureSheet, x: 34, y: 34, pass: false, spawn: false },
  { index: 34, src: natureSheet, x: 51, y: 34, pass: false, spawn: false },
  { index: 35, src: natureSheet, x: 68, y: 34, pass: false, spawn: false },
  { index: 36, src: natureSheet, x: 85, y: 34, pass: false, spawn: false },

  { index: 37, src: obstacleSheet, x: 0, y: 0, pass: false, spawn: false },
  { index: 38, src: obstacleSheet, x: 17, y: 0, pass: false, spawn: false },
  { index: 39, src: obstacleSheet, x: 34, y: 0, pass: false, spawn: false },
  { index: 40, src: obstacleSheet, x: 0, y: 17, pass: false, spawn: false },
  { index: 41, src: obstacleSheet, x: 17, y: 17, pass: false, spawn: false },
  { index: 42, src: obstacleSheet, x: 34, y: 17, pass: false, spawn: false },
  { index: 43, src: obstacleSheet, x: 0, y: 34, pass: false, spawn: false },
  { index: 44, src: obstacleSheet, x: 17, y: 34, pass: false, spawn: false },
  { index: 45, src: obstacleSheet, x: 34, y: 34, pass: false, spawn: false },
  { index: 46, src: obstacleSheet, x: 0, y: 51, pass: false, spawn: false },
  { index: 47, src: obstacleSheet, x: 17, y: 51, pass: false, spawn: false },
  { index: 48, src: obstacleSheet, x: 34, y: 51, pass: false, spawn: false },

  { index: 49, src: streetSheet, x: 0, y: 0, pass: true, spawn: false },
  { index: 50, src: streetSheet, x: 17, y: 0, pass: true, spawn: false },
  { index: 51, src: streetSheet, x: 34, y: 0, pass: true, spawn: false },
  { index: 52, src: streetSheet, x: 51, y: 0, pass: true, spawn: false },
  { index: 53, src: streetSheet, x: 0, y: 17, pass: true, spawn: false },
  { index: 54, src: streetSheet, x: 17, y: 17, pass: true, spawn: false },
  { index: 55, src: streetSheet, x: 34, y: 17, pass: true, spawn: false },
  { index: 56, src: streetSheet, x: 51, y: 17, pass: true, spawn: false },
  { index: 57, src: streetSheet, x: 0, y: 34, pass: true, spawn: false },
  { index: 58, src: streetSheet, x: 17, y: 34, pass: true, spawn: false },
  { index: 59, src: streetSheet, x: 34, y: 34, pass: true, spawn: false },
  { index: 60, src: streetSheet, x: 51, y: 34, pass: true, spawn: false },
  { index: 61, src: streetSheet, x: 0, y: 51, pass: true, spawn: false },
  { index: 62, src: streetSheet, x: 17, y: 51, pass: true, spawn: false },
  { index: 63, src: streetSheet, x: 34, y: 51, pass: true, spawn: false },
  { index: 64, src: streetSheet, x: 51, y: 51, pass: true, spawn: false },
  { index: 65, src: streetSheet, x: 0, y: 69, pass: true, spawn: false },
  { index: 66, src: streetSheet, x: 17, y: 69, pass: true, spawn: false },
  { index: 67, src: streetSheet, x: 34, y: 69, pass: true, spawn: false },
  { index: 68, src: streetSheet, x: 51, y: 69, pass: false, spawn: false },

  //häuser
  { index: 69, src: house1Sheet, x: 0, y: 0, pass: false, spawn: false },
  { index: 70, src: house1Sheet, x: 17, y: 0, pass: true, spawn: false },
  { index: 71, src: house1Sheet, x: 34, y: 0, pass: true, spawn: false },
  { index: 72, src: house1Sheet, x: 51, y: 0, pass: true, spawn: false },
  { index: 73, src: house1Sheet, x: 68, y: 0, pass: false, spawn: false },
  { index: 74, src: house1Sheet, x: 0, y: 17, pass: false, spawn: false },
  { index: 75, src: house1Sheet, x: 17, y: 17, pass: false, spawn: false },
  { index: 76, src: house1Sheet, x: 34, y: 17, pass: false, spawn: false },
  { index: 77, src: house1Sheet, x: 51, y: 17, pass: false, spawn: false },
  { index: 78, src: house1Sheet, x: 68, y: 17, pass: false, spawn: false },
  { index: 79, src: house1Sheet, x: 0, y: 34, pass: false, spawn: false },
  { index: 80, src: house1Sheet, x: 17, y: 34, pass: false, spawn: false },
  { index: 81, src: house1Sheet, x: 34, y: 34, pass: false, spawn: false },
  { index: 82, src: house1Sheet, x: 51, y: 34, pass: false, spawn: false },
  { index: 83, src: house1Sheet, x: 68, y: 34, pass: false, spawn: false },
  { index: 84, src: house1Sheet, x: 0, y: 51, pass: false, spawn: false },
  { index: 85, src: house1Sheet, x: 17, y: 51, pass: false, spawn: false },
  { index: 86, src: house1Sheet, x: 34, y: 51, pass: false, spawn: false },
  { index: 87, src: house1Sheet, x: 51, y: 51, pass: false, spawn: false },
  { index: 88, src: house1Sheet, x: 68, y: 51, pass: false, spawn: false },
  { index: 89, src: house1Sheet, x: 0, y: 68, pass: false, spawn: false },
  { index: 90, src: house1Sheet, x: 17, y: 68, pass: false, spawn: false },
  { index: 91, src: house1Sheet, x: 34, y: 68, pass: false, spawn: false },
  { index: 92, src: house1Sheet, x: 51, y: 68, pass: false, spawn: false },
  { index: 93, src: house1Sheet, x: 68, y: 68, pass: false, spawn: false },
  { index: 94, src: house1Sheet, x: 0, y: 85, pass: false, spawn: false },
  { index: 95, src: house1Sheet, x: 17, y: 85, pass: false, spawn: false },
  { index: 96, src: house1Sheet, x: 34, y: 85, pass: false, spawn: false },
  { index: 97, src: house1Sheet, x: 51, y: 85, pass: false, spawn: false },
  { index: 98, src: house1Sheet, x: 68, y: 85, pass: false, spawn: false },

  { index: 99, src: house2Sheet, x: 0, y: 0, pass: false, spawn: false },
  { index: 100, src: house2Sheet, x: 17, y: 0, pass: true, spawn: false },
  { index: 101, src: house2Sheet, x: 34, y: 0, pass: true, spawn: false },
  { index: 102, src: house2Sheet, x: 51, y: 0, pass: true, spawn: false },
  { index: 103, src: house2Sheet, x: 68, y: 0, pass: false, spawn: false },
  { index: 104, src: house2Sheet, x: 0, y: 17, pass: false, spawn: false },
  { index: 105, src: house2Sheet, x: 17, y: 17, pass: false, spawn: false },
  { index: 106, src: house2Sheet, x: 34, y: 17, pass: false, spawn: false },
  { index: 107, src: house2Sheet, x: 51, y: 17, pass: false, spawn: false },
  { index: 108, src: house2Sheet, x: 68, y: 17, pass: false, spawn: false },
  { index: 109, src: house2Sheet, x: 0, y: 34, pass: false, spawn: false },
  { index: 110, src: house2Sheet, x: 17, y: 34, pass: false, spawn: false },
  { index: 111, src: house2Sheet, x: 34, y: 34, pass: false, spawn: false },
  { index: 112, src: house2Sheet, x: 51, y: 34, pass: false, spawn: false },
  { index: 113, src: house2Sheet, x: 68, y: 34, pass: false, spawn: false },
  { index: 114, src: house2Sheet, x: 0, y: 51, pass: false, spawn: false },
  { index: 115, src: house2Sheet, x: 17, y: 51, pass: false, spawn: false },
  { index: 116, src: house2Sheet, x: 34, y: 51, pass: false, spawn: false },
  { index: 117, src: house2Sheet, x: 51, y: 51, pass: false, spawn: false },
  { index: 118, src: house2Sheet, x: 68, y: 51, pass: false, spawn: false },
  { index: 119, src: house2Sheet, x: 0, y: 68, pass: false, spawn: false },
  { index: 120, src: house2Sheet, x: 17, y: 68, pass: false, spawn: false },
  { index: 121, src: house2Sheet, x: 34, y: 68, pass: false, spawn: false },
  { index: 122, src: house2Sheet, x: 51, y: 68, pass: false, spawn: false },
  { index: 123, src: house2Sheet, x: 68, y: 68, pass: false, spawn: false },
  { index: 124, src: house2Sheet, x: 0, y: 85, pass: false, spawn: false },
  { index: 125, src: house2Sheet, x: 17, y: 85, pass: false, spawn: false },
  { index: 126, src: house2Sheet, x: 34, y: 85, pass: false, spawn: false },
  { index: 127, src: house2Sheet, x: 51, y: 85, pass: false, spawn: false },
  { index: 128, src: house2Sheet, x: 68, y: 85, pass: false, spawn: false },
  //Äcker
  { index: 129, src: acherSheet, x: 0, y: 0, pass: true, spawn: false },
  { index: 130, src: acherSheet, x: 17, y: 0, pass: true, spawn: false },
  { index: 131, src: acherSheet, x: 34, y: 0, pass: true, spawn: false },
  { index: 132, src: acherSheet, x: 0, y: 17, pass: true, spawn: false },
  { index: 133, src: acherSheet, x: 17, y: 17, pass: true, spawn: false },
  { index: 134, src: acherSheet, x: 34, y: 17, pass: true, spawn: false },

  { index: 135, src: acher2Sheet, x: 0, y: 0, pass: true, spawn: false },
  { index: 136, src: acher2Sheet, x: 17, y: 0, pass: true, spawn: false },
  { index: 137, src: acher2Sheet, x: 34, y: 0, pass: true, spawn: false },
  { index: 138, src: acher2Sheet, x: 0, y: 17, pass: false, spawn: false },
  { index: 139, src: acher2Sheet, x: 17, y: 17, pass: true, spawn: false },
  { index: 140, src: acher2Sheet, x: 34, y: 17, pass: true, spawn: false },
  { index: 141, src: acher2Sheet, x: 0, y: 34, pass: false, spawn: false },
  { index: 142, src: acher2Sheet, x: 17, y: 34, pass: false, spawn: false },
  { index: 143, src: acher2Sheet, x: 34, y: 34, pass: true, spawn: false },
  { index: 144, src: acher2Sheet, x: 0, y: 51, pass: false, spawn: false },
  { index: 145, src: acher2Sheet, x: 17, y: 51, pass: false, spawn: false },
  { index: 146, src: acher2Sheet, x: 34, y: 51, pass: false, spawn: false },
  { index: 147, src: acher2Sheet, x: 0, y: 68, pass: false, spawn: false },
  { index: 148, src: acher2Sheet, x: 17, y: 68, pass: false, spawn: false },
  { index: 149, src: acher2Sheet, x: 34, y: 68, pass: false, spawn: false },
  { index: 150, src: acher2Sheet, x: 0, y: 85, pass: false, spawn: false },
  { index: 151, src: acher2Sheet, x: 17, y: 85, pass: false, spawn: false },
  { index: 152, src: acher2Sheet, x: 34, y: 85, pass: false, spawn: false },

  { index: 153, src: restSheet, x: 0, y: 0, pass: true, spawn: false },
  { index: 154, src: restSheet, x: 17, y: 0, pass: true, spawn: false },
  { index: 155, src: restSheet, x: 34, y: 0, pass: true, spawn: false },
  { index: 156, src: restSheet, x: 51, y: 0, pass: true, spawn: false },
  { index: 157, src: restSheet, x: 68, y: 0, pass: true, spawn: false },
  { index: 158, src: restSheet, x: 85, y: 0, pass: true, spawn: false },
  { index: 159, src: restSheet, x: 102, y: 0, pass: true, spawn: false },
  { index: 160, src: restSheet, x: 119, y: 0, pass: true, spawn: false },
  { index: 161, src: restSheet, x: 0, y: 17, pass: true, spawn: false },
  { index: 162, src: restSheet, x: 17, y: 17, pass: true, spawn: false },
  { index: 163, src: restSheet, x: 34, y: 17, pass: true, spawn: false },
  { index: 164, src: restSheet, x: 51, y: 17, pass: false, spawn: false },
  { index: 165, src: restSheet, x: 68, y: 17, pass: false, spawn: false },
  { index: 166, src: restSheet, x: 85, y: 17, pass: false, spawn: false },
  { index: 167, src: restSheet, x: 102, y: 17, pass: false, spawn: false },
  { index: 168, src: restSheet, x: 119, y: 17, pass: false, spawn: false },
  { index: 169, src: restSheet, x: 0, y: 34, pass: true, spawn: false },
  { index: 170, src: restSheet, x: 17, y: 34, pass: true, spawn: false },
  { index: 171, src: restSheet, x: 34, y: 34, pass: false, spawn: false },
  { index: 172, src: restSheet, x: 51, y: 34, pass: false, spawn: false },
  { index: 173, src: restSheet, x: 68, y: 34, pass: false, spawn: false },
  { index: 174, src: restSheet, x: 85, y: 34, pass: false, spawn: false },
  { index: 175, src: restSheet, x: 102, y: 34, pass: false, spawn: false },
  { index: 176, src: restSheet, x: 119, y: 34, pass: false, spawn: false },
  { index: 177, src: restSheet, x: 0, y: 51, pass: false, spawn: false },
  { index: 178, src: restSheet, x: 17, y: 51, pass: false, spawn: false },
  { index: 179, src: restSheet, x: 34, y: 51, pass: false, spawn: false },
  { index: 180, src: restSheet, x: 51, y: 51, pass: false, spawn: false },
  { index: 181, src: restSheet, x: 68, y: 51, pass: false, spawn: false },
  { index: 182, src: restSheet, x: 85, y: 51, pass: false, spawn: false },
  { index: 183, src: restSheet, x: 102, y: 51, pass: false, spawn: false },
  { index: 184, src: restSheet, x: 119, y: 51, pass: false, spawn: false },
  { index: 185, src: restSheet, x: 0, y: 68, pass: false, spawn: false },
  { index: 186, src: restSheet, x: 17, y: 68, pass: false, spawn: false },
  { index: 187, src: restSheet, x: 34, y: 68, pass: false, spawn: false },
  { index: 188, src: restSheet, x: 51, y: 68, pass: true, spawn: false },
  { index: 189, src: restSheet, x: 68, y: 68, pass: false, spawn: false },
  { index: 190, src: restSheet, x: 85, y: 68, pass: false, spawn: false },
  { index: 191, src: restSheet, x: 102, y: 68, pass: false, spawn: false },
  { index: 192, src: restSheet, x: 119, y: 68, pass: false, spawn: false },
  { index: 193, src: restSheet, x: 0, y: 85, pass: false, spawn: false },
  { index: 194, src: restSheet, x: 17, y: 85, pass: false, spawn: false },
  { index: 195, src: restSheet, x: 34, y: 85, pass: true, spawn: false },
  { index: 196, src: restSheet, x: 51, y: 85, pass: true, spawn: false },
  { index: 197, src: restSheet, x: 68, y: 85, pass: true, spawn: false },
  { index: 198, src: restSheet, x: 85, y: 85, pass: true, spawn: false },
  { index: 199, src: restSheet, x: 102, y: 85, pass: false, spawn: false },
  { index: 200, src: restSheet, x: 119, y: 85, pass: false, spawn: false },
  { index: 201, src: restSheet, x: 0, y: 102, pass: false, spawn: false },
  { index: 202, src: restSheet, x: 17, y: 102, pass: false, spawn: false },
  { index: 203, src: restSheet, x: 34, y: 102, pass: false, spawn: false },
  { index: 204, src: restSheet, x: 51, y: 102, pass: false, spawn: false },
  { index: 205, src: restSheet, x: 68, y: 102, pass: false, spawn: false },
  { index: 206, src: restSheet, x: 85, y: 102, pass: false, spawn: false },
  { index: 207, src: restSheet, x: 102, y: 102, pass: false, spawn: false },
  { index: 208, src: restSheet, x: 119, y: 102, pass: false, spawn: false },
  { index: 209, src: restSheet, x: 0, y: 119, pass: false, spawn: false },
  { index: 210, src: restSheet, x: 17, y: 119, pass: false, spawn: false },
  { index: 211, src: restSheet, x: 34, y: 119, pass: true, spawn: false },
  { index: 212, src: restSheet, x: 51, y: 119, pass: true, spawn: false },
  { index: 213, src: restSheet, x: 68, y: 119, pass: true, spawn: false },
  { index: 214, src: restSheet, x: 85, y: 119, pass: false, spawn: false },
  { index: 215, src: restSheet, x: 102, y: 119, pass: false, spawn: false },
  { index: 216, src: restSheet, x: 119, y: 119, pass: false, spawn: false },

  { index: 217, src: rest2Sheet, x: 0, y: 0, pass: true, spawn: false },
  { index: 170, src: rest2Sheet, x: 17, y: 0, pass: false, spawn: false },
  { index: 171, src: rest2Sheet, x: 34, y: 0, pass: false, spawn: false },
  { index: 172, src: rest2Sheet, x: 51, y: 0, pass: false, spawn: false },
  { index: 173, src: rest2Sheet, x: 68, y: 0, pass: false, spawn: false },
  { index: 174, src: rest2Sheet, x: 85, y: 0, pass: false, spawn: false },
  { index: 175, src: rest2Sheet, x: 102, y: 0, pass: false, spawn: false },
  { index: 176, src: rest2Sheet, x: 119, y: 0, pass: false, spawn: false },
  { index: 177, src: rest2Sheet, x: 136, y: 0, pass: false, spawn: false },
  { index: 178, src: rest2Sheet, x: 153, y: 0, pass: false, spawn: false },
  { index: 179, src: rest2Sheet, x: 0, y: 17, pass: false, spawn: false },
  { index: 180, src: rest2Sheet, x: 17, y: 17, pass: false, spawn: false },
  { index: 181, src: rest2Sheet, x: 34, y: 17, pass: false, spawn: false },
  { index: 182, src: rest2Sheet, x: 51, y: 17, pass: false, spawn: false },
  { index: 183, src: rest2Sheet, x: 68, y: 17, pass: false, spawn: false },
  { index: 184, src: rest2Sheet, x: 85, y: 17, pass: false, spawn: false },
  { index: 185, src: rest2Sheet, x: 102, y: 17, pass: false, spawn: false },
  { index: 186, src: rest2Sheet, x: 119, y: 17, pass: false, spawn: false },
  { index: 187, src: rest2Sheet, x: 136, y: 17, pass: false, spawn: false },
  { index: 188, src: rest2Sheet, x: 153, y: 17, pass: false, spawn: false },
  { index: 189, src: rest2Sheet, x: 0, y: 34, pass: false, spawn: false },
  { index: 190, src: rest2Sheet, x: 17, y: 34, pass: false, spawn: false },
  { index: 191, src: rest2Sheet, x: 34, y: 34, pass: false, spawn: false },
  { index: 192, src: rest2Sheet, x: 51, y: 34, pass: false, spawn: false },
  { index: 193, src: rest2Sheet, x: 68, y: 34, pass: false, spawn: false },
  { index: 194, src: rest2Sheet, x: 85, y: 34, pass: false, spawn: false },
  { index: 195, src: rest2Sheet, x: 102, y: 34, pass: false, spawn: false },
  { index: 196, src: rest2Sheet, x: 119, y: 34, pass: false, spawn: false },
  { index: 197, src: rest2Sheet, x: 136, y: 34, pass: false, spawn: false },
  { index: 198, src: rest2Sheet, x: 153, y: 34, pass: false, spawn: false },
  { index: 199, src: rest2Sheet, x: 0, y: 51, pass: false, spawn: false },
  { index: 200, src: rest2Sheet, x: 17, y: 51, pass: false, spawn: false },
  { index: 201, src: rest2Sheet, x: 34, y: 51, pass: false, spawn: false },
  { index: 202, src: rest2Sheet, x: 51, y: 51, pass: false, spawn: false },
  { index: 203, src: rest2Sheet, x: 68, y: 51, pass: false, spawn: false },
  { index: 204, src: rest2Sheet, x: 85, y: 51, pass: false, spawn: false },
  { index: 205, src: rest2Sheet, x: 102, y: 51, pass: false, spawn: false },
  { index: 206, src: rest2Sheet, x: 119, y: 51, pass: false, spawn: false },
  { index: 207, src: rest2Sheet, x: 136, y: 51, pass: false, spawn: false },
  { index: 208, src: rest2Sheet, x: 153, y: 51, pass: false, spawn: false },
  { index: 209, src: rest2Sheet, x: 0, y: 68, pass: false, spawn: false },
  { index: 210, src: rest2Sheet, x: 17, y: 68, pass: false, spawn: false },
  { index: 211, src: rest2Sheet, x: 34, y: 68, pass: false, spawn: false },
  { index: 212, src: rest2Sheet, x: 51, y: 68, pass: false, spawn: false },
  { index: 213, src: rest2Sheet, x: 68, y: 68, pass: false, spawn: false },
  { index: 214, src: rest2Sheet, x: 85, y: 68, pass: false, spawn: false },
  { index: 215, src: rest2Sheet, x: 102, y: 68, pass: false, spawn: false },
  { index: 216, src: rest2Sheet, x: 119, y: 68, pass: false, spawn: false },
  { index: 217, src: rest2Sheet, x: 136, y: 68, pass: false, spawn: false },
  { index: 218, src: rest2Sheet, x: 153, y: 68, pass: false, spawn: false },
  { index: 219, src: rest2Sheet, x: 0, y: 85, pass: false, spawn: false },
  { index: 220, src: rest2Sheet, x: 17, y: 85, pass: false, spawn: false },
  { index: 221, src: rest2Sheet, x: 34, y: 85, pass: false, spawn: false },
  { index: 222, src: rest2Sheet, x: 51, y: 85, pass: false, spawn: false },
  { index: 223, src: rest2Sheet, x: 68, y: 85, pass: false, spawn: false },
  { index: 224, src: rest2Sheet, x: 85, y: 85, pass: false, spawn: false },
  { index: 225, src: rest2Sheet, x: 102, y: 85, pass: false, spawn: false },
  { index: 226, src: rest2Sheet, x: 119, y: 85, pass: false, spawn: false },
  { index: 227, src: rest2Sheet, x: 136, y: 85, pass: false, spawn: false },
  { index: 228, src: rest2Sheet, x: 153, y: 85, pass: false, spawn: false },
  //water
  { index: 229, src: waterSheet, x: 0, y: 0, pass: false, spawn: false },
  { index: 230, src: waterSheet, x: 17, y: 0, pass: false, spawn: false },
  { index: 231, src: waterSheet, x: 34, y: 0, pass: false, spawn: false },
  { index: 232, src: waterSheet, x: 51, y: 0, pass: false, spawn: false },
  { index: 233, src: waterSheet, x: 68, y: 0, pass: false, spawn: false },
  { index: 234, src: waterSheet, x: 0, y: 17, pass: false, spawn: false },
  { index: 235, src: waterSheet, x: 17, y: 17, pass: false, spawn: false },
  { index: 236, src: waterSheet, x: 34, y: 17, pass: false, spawn: false },
  { index: 237, src: waterSheet, x: 51, y: 17, pass: false, spawn: false },
  { index: 238, src: waterSheet, x: 68, y: 17, pass: false, spawn: false },
  { index: 239, src: waterSheet, x: 0, y: 34, pass: false, spawn: false },
  { index: 240, src: waterSheet, x: 17, y: 34, pass: false, spawn: false },
  { index: 241, src: waterSheet, x: 34, y: 34, pass: false, spawn: false },
  { index: 242, src: waterSheet, x: 51, y: 34, pass: false, spawn: false },
  { index: 243, src: waterSheet, x: 68, y: 34, pass: false, spawn: false },
  { index: 244, src: waterSheet, x: 0, y: 51, pass: false, spawn: false },
  { index: 245, src: waterSheet, x: 17, y: 51, pass: false, spawn: false },
  { index: 246, src: waterSheet, x: 34, y: 51, pass: false, spawn: false },
  { index: 247, src: waterSheet, x: 51, y: 51, pass: false, spawn: false },
  { index: 248, src: waterSheet, x: 68, y: 51, pass: false, spawn: false },
];

export default mapDefinition;
